[categories]
# Category IDs to explicitly allow mappings commands within - leave empty for all.
allowed = []

# Category IDs to explicitly disallow mappings commands within - leave empty for none.
banned = []

[channels]
# Channel IDs to explicitly allow mappings commands within - leave empty for all.
allowed = []

# Channel IDs to explicitly disallow mappings commands within - leave empty for none.
banned = []

[guilds]
# Guild IDs to explicitly allow mappings commands within - leave empty for all.
allowed = []

# Guild IDs to explicitly disallow mappings commands within - leave empty for none.
banned = []

[settings]
# Which namespaces to allow lookups for - only "mcp", "mojang" and "yarn" are currently supported.
namespaces = ["mcp", "mojang", "yarn"]
